---
name: Deploy to Scaleway and AWS

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  scaleway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scaleway/deploy
    steps:
      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Checkout repository
        uses: actions/checkout@v6

      - run: tofu init
      - run: tofu apply -auto-approve
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}

  aws:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws/deploy
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Checkout repository
        uses: actions/checkout@v6

      - run: go build -o bootstrap ./main.go
        working-directory: ./aws/src/

      - run: tofu init
      - run: tofu apply -auto-approve